---
title: "LABORATORIO 1 DATA WRANGLER"
author: "Keneth Ruiz"
date: "2023-08-02"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Incorporacion de librerias
```{r}
library(readxl)
library(purrr)
library(readr)
```

# Problema 1 

```{r}
carpeta <- "C:/Users/Keneth Ruiz/OneDrive/Escritorio/Datasetlab1"

### Lista de archivos Excel en la carpeta
archivos <- list.files(path = carpeta, pattern = "\\.xlsx$", full.names = TRUE)

### Importar archivos y combinar en una única tabla utilizando map_dfr
tabla_final <- map_dfr(archivos, ~ {
  datos <- read_excel(.x)
  datos$archivo <- tools::file_path_sans_ext(basename(.x))
  datos$fecha <- tools::file_path_sans_ext(basename(.x)) 
### Crear la columna "fecha"
  return(datos)
})

### Verificar la tabla final
head(tabla_final)

```
```{r}
tabla_final
```
### Nombres de cada columna
```{r}
names(tabla_final)
```
### Cantidad de documentos de excel
```{r}
# Obtener la cantidad de documentos de Excel en la tabla
num_documentos <- length(unique(tabla_final$archivo))

# Imprimir la cantidad de documentos
print(num_documentos)


```

# Problema 2 

```{r}
### Crear una lista con al menos 3 vectores
lista_vectores <- list(
  vector1 = c(1, 0, 1, 3, 1, 0, 1, 1, 1),
  vector2 = c(4, 4, 4, 4, 4, 4, 3, 4, 3),
  vector3 = c(77, 44, 77, 55, 77, 33, 77, 44, 77)
)

### Definir una función para calcular la moda de un vector
calcular_moda <- function(x) {
  tab <- table(x)
  moda <- as.numeric(names(tab)[tab == max(tab)])
  return(moda)
}

### Usar lapply para encontrar la moda de cada vector en la lista
moda_por_vector <- lapply(lista_vectores, calcular_moda)

### Mostrar los resultados
print(moda_por_vector)

```
# problema 3
```{r}
ruta <- "C:/Users/Keneth Ruiz/OneDrive/Escritorio/Datasetlab1/INE_PARQUE_VEHICULAR_080219.txt"
datos <- read_delim(ruta, delim = "\t", show_col_types = FALSE)

head(datos)


```

