install.packages("lubridate")
install.packages("rwhatsapp")
install.packages("textdata")
install.packages("tidytext")
install.packages("tidyverse")
install.packages("tidyr")
install.packages("ggimage")
install.packages("stopwords")
install.packages("ggplot2")
install.packages("igraph")
install.packages("ggraph")
install.packages("dplyr")

library(lubridate)
library(rwhatsapp)
library(textdata)
library(tidytext)
library(tidyverse)
library(tidyr)
library(ggimage)
library(stopwords)
library(ggplot2)
library(igraph)
library(ggraph)
library(dplyr)


chat <- rwa_read("_chat.txt")
